export const path = {
    HOME : '/',
    TRANGCHU: 'trangchu',
    LOGIN : 'dangnhap',
    REGISTER : 'dangky',
    FORGET: 'quenmatkhau',
    NPASSWORD: 'resetmatkhau',
    ABOUT : 'gioithieu',
    CONTACT: 'lienhe',
    ROOMS : 'xemphong',
    ORDERROOM : 'datphong',
    WISHLIST: 'yeuthich',
    ACCOUNT : 'taikhoan',
    DETAILROOM : 'chitietphong',
    TERMS: 'dieukhoan',
    POLICY: 'chinhsach',
    NEWS: 'tintuc',
    FAQ: 'faq',
}
